### PR TITLE
Opinionated refinements

### LINKED ISSUE #3: Reduce copyright info in each file header and just reference LICENSE file
Instead of that long MIT license text in each file header, we should reduce that to something like:

```
/*
 * This file is part of the rdfinterface package and licensed under the terms of the MIT-license.
 *
 * (c) XXX <YYY>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

I like the style of the Symfony project, for instance: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Form/AbstractExtension.php#L3-L10

### PR DESCRIPTION
**Pull request by k00ni**
This PR contains some (opinionated) refinements/changes.

**Summary**
* Changed content of `README.md` to make it more clear or better to read. But I am not a native English speaker.
* I removed PHPdoc entries like `@return void`, because its duplicated content (if function already defines it)
* ran codesniffer to fix some coding style issues
* added `.editorconfig`
* removed not used `use Stringable;`

What do you think? Feel free to disagree.

### CODE REVIEW

**Comment by zozlak** [comment]
> I removed PHPdoc entries like @return void, because its duplicated content (if function already defines it)

This is automatically generated by my IDE and will be back there every next time a function signature will change (which is maybe not so frequent by whatever). It also doesn't make any harm. So please let it go.

**Comment by zozlak** [comment]
I'm afraid you have just started a "spaghetti pull request" meaning you are mixing various changes in one pull request.
Please avoid it. Changes in README should be considered separate from changes in coding style.

**Comment by zozlak** [comment]
And when it comes to code formatting - we might discuss it (although I consider it very low priority until it consistently follows any convention) but at the end of a day it's anyway a matter of taste. 

Having a common taste (or at least compromise on a common taste) while developing software is important but beginning with saying "I would change it according to my taste" is not the best way of starting contributing to someones code.

**Comment by k00ni** [comment]
> Having a common taste (or at least compromise on a common taste) while developing software is important but beginning with saying "I would change it according to my taste" is not the best way of starting contributing to someones code.

Sorry if I pissed you off, that was not my intention. 

If I remember correctly you said that your main focus is not RDF + PHP anymore. Because of that I thought it is a good idea to give you a hand and provide some code suggestions. I also wanted to see, where your preferences lay so I can focus accordingly. But you are right, this PR got a little bit messy.

I will close this and make a new PR with only README.md changes.

**Pull request closed without merging**
