### PR TITLE
feat: allow psr/http-message 2.0

### PR DESCRIPTION
**Pull request by dunglas**
No other change is necessary as the types are only used in docblocks.

### CODE REVIEW

**Comment by k00ni** [comment]
@dunglas Thanks for the pull request.

[Diff](https://github.com/php-fig/http-message/compare/1.1...2.0) between 1.1 and 2.0 looks fine, I was a bit worried about PHPStan at first. @zozlak what do you think?

**Comment by dunglas** [comment]
PHPStan will not complain. The only difference between v1 and v2 is the addition of type hints.

**Comment by zozlak** [comment]
Btw, does it mean someone else than me and k00ni uses the rdfInterface?

@dunglas, if you don't mind, I would be interested in having a quick chat with you regarding your experience and expectations.

**Comment by dunglas** [comment]
Thanks for the merge. Actually this package comes as a dependency of https://github.com/sweetrdf/easyrdf that we use in https://github.com/api-platform/schema-generator

Happy to chat about this.

**Comment by zozlak** [comment]
Ah, ok, so it's just a consequence of reusing the n-triples serializer from the [rdfHelpers](https://github.com/sweetrdf/rdfHelpers) in the EasyRdf... Then I have no further questions.

**Pull request merged**
